---
title: "Dynamic report"
output: html_document
params:
  a: NA
  k: NA
  gr: NA
  results: NA
  histogram_totalscores: NA
  difPlot: NA
  hist_distractor_by_group: NA
  graf: NA
  logreg: NA
  zlogreg: NA
  zlogreg_irt: NA
  nlsplot: NA
  multiplot: NA
  twoparam: NA
  twoparamiic: NA
  twoparamtif: NA
  twoparamcoef: NA
  twofactor: NA
  resultsgroup: NA
  histbyscoregroup0: NA
  histbyscoregroup1: NA
  deltaplot: NA
  DP_text_normal: NA
  DIF_logistic_print: NA
  DIF_logistic_plot: NA
  plot_DIF_logistic: NA
  plot_DIF_logistic_IRT_Z: NA
  plot_DIF_NLR: NA
  plot_DIF_IRT_Lord: NA
  plot_DIF_IRT_Raju: NA
  itemexam: NA
---
# Summary Report
```{r echo=FALSE}
params$results
params$histogram_totalscores
```

# Traditional Analysis Report
```{r echo=FALSE}
params$difPlot
params$itemexam
```
# Regression Report
```{r echo=FALSE}
params$graf
# params$logreg
# params$zlogreg
# params$zlogreg_irt
# params$nlsplot
params$multiplot
```

```{r echo=FALSE}
# params$plot_DIF_logistic
# params$plot_DIF_logistic_IRT_Z
# params$plot_DIF_NLR
# params$plot_DIF_IRT_Lord
# params$plot_DIF_IRT_Raju
```
# IRT Model Report

$\\mathrm{P}\\left(Y_{ij} = 1\\vert \\theta_{i}, a_{j}, b_{j}\\right) =  \\frac{e^{a_{j}\\left(\\theta_{i}-b_{j}\\right) }}{1+e^{a_{j}\\left(\\theta_{i}-b_{j}\\right) }} $

```{r echo=FALSE}
params$twoparam
params$twoparamiic
params$twoparamtif
params$twoparamcoef
params$twofactor
```

# DIF/Fairness Report

```{r echo=FALSE}
params$resultsgroup
params$histbyscoregroup0
params$histbyscoregroup1
params$deltaplot
params$DP_text_normal
params$DIF_logistic_print
params$DIF_logistic_plot
```

