theme_shiny <- theme(panel.border = element_rect(fill = NA, colour = "grey20"),
                     strip.background = element_rect(fill = "grey85", colour = "grey20"),
                     legend.key = element_rect(fill = "white", colour = NA),
                     legend.title = element_blank(),
                     axis.line  = element_line(colour = "black"),
                     panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(),
                     panel.background = element_blank(),
                     text = element_text(size = 14),
                     legend.position = "none",
                     plot.title = element_text(face = "bold"))
