---
title: "Item Analysis Report"
date: '`r format(Sys.Date(), "%d %B, %Y")`'
output: 
    pdf_document:
       number_sections: true
params:
  a: NA
  k: NA
  gr: NA
  results: NA
  histogram_totalscores: NA
  difPlot: NA
  hist_distractor_by_group: NA
  graf: NA
  logreg: NA
  zlogreg: NA
  zlogreg_irt: NA
  nlsplot: NA
  multiplot: NA
  irt: NA
  irtiic: NA
  irttif: NA
  irtcoef: NA
  irtfactor: NA
  resultsgroup: NA
  histbyscoregroup0: NA
  histbyscoregroup1: NA
  deltaplot: NA
  DP_text_normal: NA
  DIF_logistic_print: NA
  DIF_logistic_plot: NA
  plot_DIF_logistic: NA
  plot_DIF_logistic_IRT_Z: NA
  plot_DIF_NLR: NA
  plot_DIF_IRT_Lord: NA
  plot_DIF_IRT_Raju: NA
  itemexam: NA
  itemReport: NA
  irt_type: NA
---
# Summary Report

```{r echo=FALSE, results="hide"}
library(gridExtra)
params$irt_report
table=params$results
table=round(table, digits=4)
colnames(table)=NULL
table=tableGrob(t(table))
hist=ggplotGrob(params$histogram_totalscores)
lay=rbind(c(1,1,1),
          c(2,2,2),
          c(2,2,2),
          c(2,2,2),
          c(2,2,2))
grid.arrange(table, hist, ncol=1, top="Basic Summary and Histogram", layout_matrix=lay)

```



\pagebreak


# Traditional Analysis Report

## Item Analysis

```{r echo=FALSE, results="hide"}
params$difPlot
```

```{r echo=FALSE, fig.height=8}
#params$itemexam
table=params$itemexam
table=format(round(table, 4), nsmall=3)
colnames(table)=c("Item", "Diff.", "SD", "D. ULI", "D. RIT", "D. RIR", "Alpha Drop")
rownames(table)=NULL
#grid.table(table)
table
```

## Distractor Analysis

```{r echo=FALSE, results="hide", fig.width=10}
for (i in 1:length(params$graf)) {
grid.arrange(params$graf[[i]], params$multiplot[[i]], ncol=2, 
             top=textGrob(paste0("Distractor and Multinomial Plots for item ",i), gp=gpar(fontsize=15))
             #,heights=unit(1.0, "npc")
             )
}
```


\pagebreak


```{r echo=FALSE, results="hide"}
if (params$irt_type=="1pl") {
head="# IRT 1PL (Rasch) Model Report"
#eq="$$ {P}(Y_{ij} = 1|\theta_{i},a,b_j) =\frac{e^{a(\theta_i-b_j)}}{1+e^{a(\theta_i-b_j)}}$$"
}

if (params$irt_type=="2pl") {
head="# IRT 2PL Model Report"
#eq="$$ {P}(Y_{ij} = 1|\theta_{i},a_j,b_j) = \frac{e^{a_j(\theta_i-b_j)}}{1+e^{a_j(\theta_i-b_j)}}$$"
}

if (params$irt_type=="3pl") {
head="# IRT 3PL Model Report"
#eq="$$ {P}(Y_{ij} = 1|\theta_{i},a_j,b_j, c_j) =c_j + (1+c_j)\cdot\frac{e^{a_j(\theta_i-b_j)}}{1+e^{a_j(\theta_i-b_j)}}$$"
}
```


`r head`

$$ {P}(Y_{ij} = 1|\theta_{i},a,b_j) =\frac{e^{a(\theta_i-b_j)}}{1+e^{a(\theta_i-b_j)}}$$

$$ {P}(Y_{ij} = 1|\theta_{i},a_j,b_j) = \frac{e^{a_j(\theta_i-b_j)}}{1+e^{a_j(\theta_i-b_j)}}$$

$$ {P}(Y_{ij} = 1|\theta_{i},a_j,b_j, c_j) =c_j + (1+c_j)\cdot\frac{e^{a_j(\theta_i-b_j)}}{1+e^{a_j(\theta_i-b_j)}}$$

```{r echo=FALSE, results="hide"}
params$irt
params$irtiic
params$irttif
```

```{r echo=FALSE}
table=params$irtcoef
table=round(table,5)
table
```

```{r echo=FALSE, results="hide"}
params$irtfactor
```


\pagebreak


# DIF/Fairness Report

## Total Scores

```{r echo=FALSE, results="hide"}
params$resultsgroup
g1=params$histbyscoregroup0
g2=params$histbyscoregroup1
grid.arrange(g1, g2, ncol=1)
```

## Delta Plot Report

```{r echo=FALSE, results="hide"}
params$deltaplot
```

```{r echo=FALSE}
params$DP_text_normal
```

## DIF Logistic Report

```{r echo=FALSE}
params$DIF_logistic_print
```

```{r echo=FALSE, results='hide'}
params$DIF_logistic_plot
```

\pagebreak
